In [1]:
import numpy as np

In [2]:
a=np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [5]:
a=np.array([1,2,3,4]) #give list or tuple like :: a=np.array((1,2,3,4))

In [4]:
a

array([1, 2, 3, 4])

In [6]:
b=np.array(50)  #one dim array

In [7]:
b

array(50)

In [10]:
c=np.array([[1,2,3],[4,5,6]])  #for a 2d array give 2 lists/tuples in a single list/tuple

In [11]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]]])  # for a 3d array 

In [13]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]]])

In [19]:
print("a dimension is :"+str(a.ndim))  # ndim gives the dimension of array 

print("b dimension is :"+str(b.ndim))
print("c dimension is :"+str(c.ndim))
print("d dimension is :"+str(d.ndim))

a dimension is :1
b dimension is :0
c dimension is :2
d dimension is :3


In [20]:
type(a)            #nd array is tensor 

numpy.ndarray

In [21]:
type(b)

numpy.ndarray

In [22]:
l=[1,2,3,4]

In [23]:
l

[1, 2, 3, 4]

In [24]:
l

[1, 2, 3, 4]

In [25]:
res=np.asarray(l,dtype='float',order='C')  
#asarray(a, dtype=None, order=None('C' for row major 'F' for colum major), *, like=None)

In [26]:
res

array([1., 2., 3., 4.])

In [27]:
res1=np.asarray(c,dtype='float',order='F')

In [28]:
res1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
res1=np.asarray(c,dtype='int',order='F')

In [30]:
res1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
#nditer is used for printing the array in one dimension
# also we can check whether they are in row major or column major 
for i in np.nditer(res1):
    print(i)

1
4
2
5
3
6


In [33]:
res2=np.asarray(c,dtype='int',order='C')

In [34]:
res2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
for i in np.nditer(res2):
    print(i)

1
2
3
4
5
6


In [36]:
#frombuffer 

In [37]:
#s= 'Welcome'      => this is a string 
#s=b'welcome'      => this is not a string it is considered as byte 
s=b'hello all this is golu'

In [38]:
s

b'hello all this is golu'

In [39]:
s.dtype

AttributeError: 'bytes' object has no attribute 'dtype'

In [40]:
#frombuffer(buffer, dtype=float, count=-1, offset=0, *, like=None)
#count is -1 means Consider all the bytes in the buffer 
#else mention the count value 
#offset is from where we have to start considering to change from buffer to array ,if it is 0 means from starting

c1=np.frombuffer(s,dtype='S1',count=-1,offset=0)

In [41]:
c1

array([b'h', b'e', b'l', b'l', b'o', b' ', b'a', b'l', b'l', b' ', b't',
       b'h', b'i', b's', b' ', b'i', b's', b' ', b'g', b'o', b'l', b'u'],
      dtype='|S1')

In [42]:
c1=np.frombuffer(s,dtype='S1',count=9,offset=2)

In [43]:
c1

array([b'l', b'l', b'o', b' ', b'a', b'l', b'l', b' ', b't'], dtype='|S1')

In [56]:
list=[10,20,30,40,55]

In [46]:
#fromiter  i.e, from iterables that is list or tuples 
# fromiter(iter, dtype, count=-1, *, like=None)
d1=np.fromiter(list,dtype='float',count=4)

In [47]:
d1

array([10., 20., 30., 40.])

In [57]:
list

[10, 20, 30, 40, 55]

In [58]:
d1=np.fromiter(list,dtype='S1',count=-1)

In [59]:
d1

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [ ]:
#arange(),linspace(),logspace() will take numerical range as input and
#return array with values in given range and required data type.
#start index(included),stop index(excluded)

#np.arange([start,] stop[, step,], dtype=None, *, like=None)
#Return evenly spaced values within a given interval.

#arange : with the step size specified instead of the number of samples.
#linspace : with the samples uniformly distributed in linear space.

In [66]:
np.arange(0,12,2,dtype='int')  # this will create a list 

array([ 0,  2,  4,  6,  8, 10])

In [64]:
arr=np.arange(0,12,2,dtype='int')  
print(arr)                            #this will be an array

[ 0  2  4  6  8 10]


In [70]:
#np.linspace(start index,stop index,num=50(default),endpoint=True(stop index included),retstep=False,dtype=None,axis=0)
#retstep is difference between numbers 
arr1=np.linspace(0,10,num=5,endpoint=True,retstep=True)

In [71]:
print(arr1)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)


In [72]:
arr2=np.linspace(0,10,num=5,endpoint=True)
print(arr2)

[ 0.   2.5  5.   7.5 10. ]


In [76]:
arr3=np.linspace(0,10) 
print(arr3)                    #by default 50 divisions and endpoint=true

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [77]:
arr4=np.linspace(0,10,endpoint=False)
print(arr4)  

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [78]:
arr5=np.linspace(0,10,endpoint=False,dtype='int')
print(arr5)  

[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5 6 6 6 6 6 7 7
 7 7 7 8 8 8 8 8 9 9 9 9 9]


In [91]:
#np.logspace(start,stop,num=50,endpoint=True,base=10.0,dtype=None,axis=0,)
ar1=np.logspace(0,10,5,endpoint=False,base=2)
print(ar1)

[  1.   4.  16.  64. 256.]


In [92]:
ar2=np.logspace(0,10,endpoint=False,base=2)
print(ar2)

[  1.           1.14869835   1.31950791   1.51571657   1.74110113
   2.           2.29739671   2.63901582   3.03143313   3.48220225
   4.           4.59479342   5.27803164   6.06286627   6.96440451
   8.           9.18958684  10.55606329  12.12573253  13.92880901
  16.          18.37917368  21.11212657  24.25146506  27.85761803
  32.          36.75834736  42.22425314  48.50293013  55.71523605
  64.          73.51669472  84.44850629  97.00586026 111.4304721
 128.         147.03338944 168.89701258 194.01172051 222.8609442
 256.         294.06677888 337.79402516 388.02344103 445.72188841
 512.         588.13355776 675.58805032 776.04688205 891.44377682]


In [105]:
#shape returns tuple specifying indices(no.of rows) and no. of elements for each index. 
#np.shape(a)  Return the shape of an array.

print(np.shape(c))
print(c)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [107]:
#reshape to change dim of array 
#np.reshape(a, newshape, order='C') -->Gives a new shape to an array without changing its data.
#imp: total no.of elements should be same
c=np.reshape(c,(3,2))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [93]:
#zeros(shape, dtype=float, order='C', *, like=None)
#Return a new array of given shape and type, filled with zeros.
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [94]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [96]:
#np.full(shape,default value,dtype(optional))
np.full((2,3),6,dtype="int")

array([[6, 6, 6],
       [6, 6, 6]])

In [109]:
#takes square matrix and initialize 1 in diagonal and remaining zeros 
#np.eye(no.of rows,dtype)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#accessing is easy 
#arr[index,index,..]

In [114]:
#slicing  [ start : stop(excluded) : stepsize ]
#deafult values like [0 : length : 1]
a1=np.array([10,20,30,40,50,60])
a1[1:4:2]

array([20, 40])

In [117]:
a2=np.array([[10,20,30],[40,50,60]])
a2[0,0:2]

array([10, 20])

In [120]:
a2[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [122]:
a2[-1,-2]

50

In [2]:
#axis=0 column
#axis=1 row
a3=np.array([[4,6,2],[9,2,3]])
a3

array([[4, 6, 2],
       [9, 2, 3]])

In [130]:
#np.sort(a, axis=-1, kind=None, order=None)
#Return a sorted copy of an array.
np.sort(a3,axis=0)


array([[4, 2, 2],
       [9, 6, 3]])

In [127]:
np.sort(a3,axis=1)

array([[2, 4, 6],
       [2, 3, 9]])

In [ ]:
#              copy()                                                              view()
#           external copy                                                reference to existing array
#  if any one element is modified not reflect to another                  modification is reflected
#             two arrays                                                       only one array 

In [11]:
#a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
#Copy of the array, cast to a specified type.
a3[1,1]=0
b3=a3.astype('bool')
b3


array([[ True,  True,  True],
       [ True, False,  True]])

In [12]:
#joining two arrays  : concatenate(name of ar1,ar2 )(join 2 arrays w.r.t given axis)
# stack(ar1,ar2)
#vstack(ar1,ar2)
#hstack(ar1,ar2)
#dstack(ar1,ar2)

In [14]:
ar1=np.arange(6).reshape(2,3)
ar1

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
ar2=np.arange(7,13).reshape(2,3)
ar2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [16]:
np.concatenate((ar1,ar2),axis=1)

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [17]:
np.concatenate((ar1,ar2),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.stack((ar1,ar2))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
np.stack((ar1,ar2),axis=1)

array([[[ 0,  1,  2],
        [ 7,  8,  9]],

       [[ 3,  4,  5],
        [10, 11, 12]]])

In [22]:
np.vstack((ar1,ar2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.hstack((ar1,ar2))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [25]:
np.dstack((ar1,ar2))

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])

In [26]:
ar3=np.arange(1,11)
ar3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#np.split(ary, indices_or_sections, axis=0)
#Split an array into multiple sub-arrays as views into `ary`.
np.split(ar3,2)          #works only in case of equal divisions 

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [28]:
np.split(ar3,3)

ValueError: array split does not result in an equal division

In [32]:
#np.array_split(ary, indices_or_sections, axis=0)
#Split an array into multiple sub-arrays.
np.array_split(ar3,2) 
#adjust the elements from last part of array

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [31]:
np.array_split(ar3,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]

In [33]:
ar3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.hsplit(ar3,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [38]:
np.vsplit(ar3,2)   
#ValueError('vsplit only works on arrays of 2 or more dimensions')

ValueError: vsplit only works on arrays of 2 or more dimensions

In [41]:
c=np.array([[1,2,3],[4,5,6]]) 
c

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
 np.vsplit(c,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [47]:
#searching in numpy
#where() => returns index of given value
#where(condition, [x, y], /)
#Return elements chosen from `x` or `y` depending on `condition`
n=np.arange(10,100,10)
n

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
np.where(n%20==0)

(array([1, 3, 5, 7], dtype=int64),)

In [53]:
np.where(n==70)

(array([6], dtype=int64),)

In [54]:
n1=np.array([5,4,6,5,3,5,8,5,2,5])
n1

array([5, 4, 6, 5, 3, 5, 8, 5, 2, 5])

In [55]:
np.where(n1==5)

(array([0, 3, 5, 7, 9], dtype=int64),)

In [60]:
#np.searchsorted(a, v, side='left', sorter=None)
#Find indices where elements should be inserted to maintain order.
#array should be in sorted order ,it will perform binary operation
print(n)
np.searchsorted(n,45)

[10 20 30 40 50 60 70 80 90]


4

In [61]:
np.searchsorted(n,[32,45,12])  #for multiple elements

array([3, 4, 1], dtype=int64)

In [66]:
print(n1)
np.sort(n1)

[5 4 6 5 3 5 8 5 2 5]


array([2, 3, 4, 5, 5, 5, 5, 5, 6, 8])

In [68]:
n2=np.array([[50,40,30],[20,10,90]])
np.sort(n2,axis=0)

array([[20, 10, 30],
       [50, 40, 90]])

In [69]:
np.sort(n2,axis=1)

array([[30, 40, 50],
       [10, 20, 90]])

In [70]:
np.sort(n2,axis=-1)

array([[30, 40, 50],
       [10, 20, 90]])

In [74]:
#np.sort(array, axis=-1, kind=sorting technique, order=None)
#Return a sorted copy of an array.
# by default it will do quick sort 

d1=np.dtype([('name','S10'),('percent',float)])
darr=np.array([('abc',92.5),('def',67.9),('ghi',98.5)],dtype=d1)
darr

array([(b'abc', 92.5), (b'def', 67.9), (b'ghi', 98.5)],
      dtype=[('name', 'S10'), ('percent', '<f8')])

In [75]:
np.sort(darr,order='percent')

array([(b'def', 67.9), (b'abc', 92.5), (b'ghi', 98.5)],
      dtype=[('name', 'S10'), ('percent', '<f8')])

In [77]:
n3=np.array([[1,2,3],[4,5,6],[7,8,9]])
n4=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [78]:
np.add(n3,n4)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [79]:
n5=np.array([3,4,5])

In [80]:
np.add(n4,n5)

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [83]:
np.add(n3,3)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
np.subtract(n3,n4)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
np.subtract(n3,5)

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [84]:
np.multiply(n3,n5)

array([[ 3,  8, 15],
       [12, 20, 30],
       [21, 32, 45]])

In [85]:
np.divide(n3,n4)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [86]:
np.power(n3,n5)

array([[    1,    16,   243],
       [   64,   625,  7776],
       [  343,  4096, 59049]])

In [87]:
np.mod(n3,n5)

array([[1, 2, 3],
       [1, 1, 1],
       [1, 0, 4]])

In [88]:
np.reciprocal(n3)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [89]:
f=np.array([0.5,0.3,0.6])
np.reciprocal(f)

array([2.        , 3.33333333, 1.66666667])

In [91]:
complex=np.array([5+6j,10-5j,9+7j])
complex

array([ 5.+6.j, 10.-5.j,  9.+7.j])

In [92]:
np.real(complex)

array([ 5., 10.,  9.])

In [93]:
np.imag(complex)

array([ 6., -5.,  7.])

In [94]:
np.conjugate(complex)

array([ 5.-6.j, 10.+5.j,  9.-7.j])

In [96]:
n6=np.array([[4,9,8],[5,7,6],[1,2,3]])
n6

array([[4, 9, 8],
       [5, 7, 6],
       [1, 2, 3]])

In [97]:
np.amin(n6)

1

In [98]:
np.amax(n6)

9

In [100]:
np.amin(n6,axis=0)

array([1, 2, 3])

In [102]:
np.amin(n6,axis=1)

array([4, 5, 1])

In [103]:
np.amax(n6,axis=0)

array([5, 9, 8])

In [104]:
np.amax(n6,axis=1)

array([9, 7, 3])

In [105]:
np.average(n6)

5.0

In [107]:
#weighted average 
w=[1,2,3]
np.average(n6,weights=w,axis=0)

array([2.83333333, 4.83333333, 4.83333333])

In [108]:
np.average(n6,weights=w,axis=1)

array([7.66666667, 6.16666667, 2.33333333])

In [109]:
np.median(n6)

5.0

In [110]:
np.median(n6,axis=0)

array([4., 7., 6.])

In [111]:
np.median(n6,axis=1)

array([8., 6., 2.])

In [112]:
np.var(n6)

6.666666666666667

In [113]:
np.std(n6)

2.581988897471611